### ISSUE TITLE
discrepancy btw section metadata  and section annotation for recording

### ISSUE THREAD

**Issue by georgid** [sertansenturk/turkish_makam_corpus_stats#1]
https://github.com/sertansenturk/turkish_makam_corpus_stats/blob/master/data/SymbTrData/ussak--sarki--duyek--aksam_oldu_huzunlendim--semahat_ozdenses.json has 6 sections while annotations to recording are for 8 sections which is more reasonable:
https://github.com/MTG/turkish_makam_section_dataset/blob/master/audio_metadata/43745ff1-0848-4592-b1ad-9e7b172b0ebd.json
@sertansenturk

**Comment by sertansenturk** [comment]
Thanks for reporting the score was missing the section ending mark

**Comment by georgid** [comment]
After @sertansenturk updated the score section annotations https://github.com/sertansenturk/turkish_makam_corpus_stats/blob/master/data/SymbTrData/ussak--sarki--duyek--aksam_oldu_huzunlendim--semahat_ozdenses.json

When I call 
dunya.docserver.get_document_as_json('c6e43ac6-4a18-42ab-bcc4-46e29360051e', "metadata", "metadata", 1, version="0.1") 
I still get the wrong metadata. I suppose the URL from where the API gets data should be updated.
